config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }, skip: [:registrations]

  resources :articles, param: :slug do
    collection do
      get :load_more
    end
    resources :comments, only: [:edit, :create, :update, :destroy, :show]
    member do
      post "like"
    end
  end

  root "articles#index"

  namespace :api do
    namespace :v1 do
      post "uploads", to: "uploads#create"
    end
  end
end

app/models/comment.rb
require "down"
require "aws-sdk-rekognition"

class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user, optional: true
  has_rich_text :content

  validate :content_presence
  validate :content_length
  validate :validate_attachment_size
  validate :validate_attachment_content_type
  validates :username, presence: {message: "Nazwa użytkownika nie może być pusta"}, length: {maximum: 25, message: "Nazwa użytkownika nie może być dłuższa niż 25 znaków"}, unless: -> { user.present? }
  validate :rate_limit, on: :create
  validate :restricted_username

  after_save :moderate_images

  private

  def content_presence
    if content.to_plain_text.blank? && !contains_image?
      errors.add(:content, "Treść komentarza nie może być pusta")
    end
  end

  def content_length
    if content.to_plain_text.length > 10000
      errors.add(:content, "Treść komentarza nie może przekraczać 10000 znaków")
    end
  end

  def contains_image?
    content.body.attachments.any?(&:image?)
  end

  def rate_limit
    comments_count = Comment.where("created_at >= ?", 1.hour.ago).count
    if comments_count >= 100
      errors.add(:base, "Wykryto przeciążenie bazy danych komentarzami.")
    end
  end

  def restricted_username
    if username.present? && username.downcase.include?("tomek in")
      errors.add(:username, "Nazwa użytkownika jest podobna do nazwy administratora.")
    end
  end

  def validate_attachment_size
    max_size_in_megabytes = 10
    content.body.attachments.each do |attachment|
      if attachment.attachable.is_a?(ActiveStorage::Blob) && attachment.byte_size > max_size_in_megabytes.megabytes
        errors.add(:content, "Rozmiar pliku nie może przekraczać 10 MB")
      end
    end
  end

  def validate_attachment_content_type
    allowed_types = ["image/jpeg", "image/png", "image/gif"]
    content.body.attachments.each do |attachment|
      unless allowed_types.include?(attachment.content_type)
        errors.add(:content, "Dozwolone są tylko pliki JPEG, PNG, GIF")
      end
    end
  end

  def moderate_images
    content.body.attachments.each do |attachment|
      if attachment.is_a?(ActionText::Attachables::RemoteImage)
        moderate_remote_image(attachment)
      elsif attachment.respond_to?(:image?) && attachment.image?
        moderate_active_storage_image(attachment)
      end
    end
  end

  def moderate_active_storage_image(attachment)
    moderation_service = ImageModerationService.new(attachment.key)
    if moderation_service.moderate_image
      moderation_service.delete_image
      attachment.purge
      errors.add(:content, "Obraz zawiera nieodpowiednie treści")
      raise ActiveRecord::RecordInvalid.new(self)
    end
  end

  def moderate_remote_image(attachment)
    # dokonczyc moderację
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :set_article
  before_action :set_comment, only: [:edit, :update, :destroy]

  def show
    respond_to do |format|
      format.html { redirect_to @article }
      format.turbo_stream { render turbo_stream: turbo_stream.replace(dom_id(@comment), partial: "comments/comment", locals: {comment: @comment}) }
    end
  end

  def create
    @comment = @article.comments.build(comment_params)

    if user_signed_in?
      @comment.user = current_user
    else
      @comment.username = params[:comment][:username]
    end

    if @comment.save
      session[:comment_ids] ||= []
      session[:comment_ids] << @comment.id

      @comments = @article.comments.order(created_at: ((session[:comment_sort_order] == "newest") ? :desc : :asc))

      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = "Komentarz dodany" }
        format.html { redirect_to @article, notice: "Komentarz dodany." }
      end
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("new_comment_form", partial: "comments/form", locals: {article: @article, comment: @comment}) }
        format.html { redirect_to @article, alert: "Komentarz nie może być utworzony" }
      end
    end
  end

  def destroy
    @comment = @article.comments.find(params[:id])

    if can_delete_comment?(@comment)
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to @article, notice: "Komentarz usunięty" }
        format.turbo_stream do
          flash.now[:notice] = "Komentarz usunięty"
          render turbo_stream: [
            turbo_stream.remove(@comment),
            turbo_stream.append("flash-messages", partial: "shared/flash_messages")
          ]
        end
      end
    else
      redirect_to @article, alert: "Nie masz uprawnień do usunięcia tego komentarza"
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.turbo_stream do
          flash.now[:notice] = "Komentarz zaktualizowany"
          render turbo_stream: [
            turbo_stream.replace(@comment, partial: "comments/comment", locals: {comment: @comment}),
            turbo_stream.append("flash-messages", partial: "shared/flash_messages")
          ]
        end
        format.html { redirect_to @comment.article, notice: "Komentarz zaktualizowany." }
      else
        format.turbo_stream do
          flash.now[:alert] = "Nie udało się zaktualizować komentarza."
          render turbo_stream: turbo_stream.replace(dom_id(@comment), partial: "comments/edit_form", locals: {comment: @comment, article: @article})
        end
        format.html do
          flash.now[:alert] = "Nie udało się zaktualizować komentarza."
          render :edit, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    respond_to do |format|
      format.turbo_stream { render partial: "comments/edit_form", locals: {comment: @comment, article: @article} }
      format.html { render partial: "comments/edit_form", locals: {comment: @comment, article: @article} }
    end
  end

  private

  def set_article
    @article = Article.find_by!(slug: params[:article_slug])
  rescue ActiveRecord::RecordNotFound
    redirect_to articles_path, alert: "Wystąpił błąd."
  end

  def set_comment
    @comment = @article.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :username)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  # def can_delete_comment?(comment)
  #   return true if user_signed_in? && (comment.user == current_user || current_user.admin?)
  #   return true if session[:comment_ids]&.include?(comment.id)

  #   false
  # end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>
  <div  class=" border-b p-4 mb-10 mt-8 rounded-lg hover:bg-[#222224]">
    <div class="flex justify-between items-center">
      <% user_display_name = comment.user&.display_name || comment.username %>
      <strong class="text-orange-600 text-xl comment-username  <%= 'text-lime-600' if user_display_name == 'Tomek InvesTB' %>">
        <span class="user-comment-icon"></span>
        <%= comment.user ? comment.user.display_name : comment.username %>
      </strong>
      <% if can_delete_comment?(comment) %>
        <div class="flex">
          <div class="relative">
            <input type="checkbox" id="<%= dom_id(comment, :sortbox) %>" class="hidden absolute">
            <label for="<%= dom_id(comment, :sortbox) %>" class="flex items-center space-x-1 cursor-pointer">
              <span class="edit-menu-comment"></span>
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
              </svg>
            </label>
            <div class="sortboxmenu absolute mt-1 right-1 top-full min-w-max shadow rounded-2xl opacity-0 bg-gray-300 border border-gray-400 transition delay-75 ease-in-out z-10">
              <ul class="block text-right text-gray-900">
                <li><a class="block px-3 py-2 hover:bg-gray-400  duration-300 m-4 rounded"><%= button_to '', edit_article_comment_path(@article, comment), method: :get, class: "btn-edit icon-edit", data: { turbo_frame: dom_id(comment) } %></a></li>
                <li>
                  <%= render 'comments/delete_modal', article: @article, comment: comment %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <p class="text-sm text-slate-400 mb-10 ">
      <%= comment.created_at.strftime('%d-%m-%Y %H:%M') %>
    </p>
    <p  class="comment-content"><%= comment.content.body.to_s %></p>
  </div>
<% end %>

app/views/comments/_delete_modal.html.erb
<div data-controller="dialog" data-action="click->dialog#backdropClose">
  <dialog data-dialog-target="dialog" class="modal">
    <p class="modal-content">Czy chcesz skasować komentarz?</p>
    <div class="modal-actions">
      <%= button_to '', article_comment_path(@article, comment), method: :delete, class: "btn-delete icon-trash modal-delete" %>
      <button type="button" data-action="dialog#close" class="modal-cancel" autofocus>Anuluj</button>
    </div>
  </dialog>
  <a class="block px-3 py-2 hover:bg-gray-400 duration-300 m-4 rounded">
    <button type="button" data-action="dialog#open" class="btn-delete icon-trash"></button>
  </a>
</div>

app/views/comments/_edit_form.html.erb
<%= turbo_frame_tag dom_id(comment)  do %>
  <%= form_with(model: [article, comment], local: true, id: "new_comment_form_#{article.slug}") do |form| %>
    <% if form.object.errors.any? %>
      <div id="error_explanation", class="error-container justify-center flex bg-slate-400 rounded-lg text-black mb-2">
        <ul>
          <% form.object.errors.full_messages.each do |message| %>
            <% message = message.sub("Content ", "").sub("Username ", "") %>
            <li>-<%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    Użytkownik: <strong><%= comment.user ? comment.user.display_name : comment.username %></strong>
    <div class="field">
      <%= form.label "comment_content", "Edytuj komentarz:" %>
      <%= form.rich_text_area :content, id: 'comment_content' %>
    </div>
    <div class="actions justify-end flex mr-2 mt-2">
      <div>
        <%= button_tag(type: 'submit', class: 'btn-accept-comment mt-2 mr-8') do %>
        </div>
        <div class="mt-2 ml-5">
          <%= link_to 'Anuluj', article_comment_path(@article, comment), class: 'btn-cancel', data: { turbo_frame: dom_id(comment) } %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= turbo_frame_tag  "new_comment_form" do %>
  <%= form_with(model: [article, comment], local: true, id: "new_comment_form_#{article.slug}") do |form| %>
      <% unless user_signed_in? %>
      <div class="flex items-center justify-between">
        <div class="field ml-2 flex-grow">
          <%= form.text_field :username, value: form.object.username, placeholder: "Autor", class: 'bg-[#222224] p-2 rounded-2xl  w-44', autocomplete: "off", id: 'comment_username' %>
        </div>
        <%= link_to 'https://docs.aws.amazon.com/rekognition/latest/dg/moderation.html', target: "_blank" do %>
          <%= image_tag 'rekognition.png', class: 'h-14 ml-2 mr-2 rounded-lg mb-2 shadow-2xl opacity-50 hover:opacity-90 transition' %>
        <% end %>
      </div>
    <% end %>
    <div class="field bg-[#222224] p-2 rounded-2xl">
      <%= form.rich_text_area :content, placeholder: "Treść komentarza", id: 'comment_content' %>
    </div>
    <div class="actions justify-end flex mr-10 mt-2">
      <%= button_tag(type: 'submit', class: 'svg-button-comment') do %>
      <% end %>
    </div>
     <% if form.object.errors.any? %>
      <div id="error_explanation", class="error-container justify-center flex bg-slate-400 rounded-lg text-black mb-2">
        <ul>
          <% form.object.errors.full_messages.each do |message| %>
            <% message = message.sub("Content ", "").sub("Username ", "") %>
            <li>-<%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.update "new_comment_form" do %>
  <%= render partial: "comments/form", locals: { article: @article, comment: Comment.new(username: @comment.username) } %>
<% end %>

<%= turbo_stream.prepend "flash", partial: "shared/flash_messages" %>

<%= turbo_stream.replace "comments" do %>
  <%= render partial: "articles/comments", locals: { comments: @article.comments.order(created_at: (session[:comment_sort_order] == 'newest' ? :desc : :asc)) } %>
<% end %>

<%= turbo_stream.update "no-comment-info" %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment) %>